### PR TITLE
fixed?

### LINKED ISSUE #129: Get user by uuid
What has to be done:
Get user by uuid

Why it has to be done:
Get user by uuid

When the task is done:
Get user by uuid

### PR DESCRIPTION
**Pull request by lfb0801**
closes #129
Not tested but it should work
re 👏 view 👏

### CODE REVIEW

File: src/main/java/com/fontys/api/service/UserService.java [hunk 1]
```diff
@@ -38,7 +39,13 @@ public String deleteUser(String uuid) {
     public List<User> getAllUsers() { return userRepository.findAll(); }
 
     @Transactional(readOnly = true)
-    public Optional<User> getUser(Integer id) { return userRepository.findById(id); }
+    public Optional<User> getUser(@Nullable Integer id, @Nullable String uuid) {
+        if (id != null)
+            return userRepository.findById(id);
+        if (uuid != null)
+            return userRepository.findByUuid(uuid);
```
Comment (MindHawk) [inline src/main/java/com/fontys/api/service/UserService.java:46]: Finding by uuid should have priority over finding by ID

**Review by MindHawk — CHANGES_REQUESTED** [review]
Lloyd said "was untested", can you just check in graphiql real quick?

**Review by MindHawk — DISMISSED** [review]

**Review by chf3kl9 — DISMISSED** [review]

**Review by MindHawk — APPROVED** [review]

**Review by chf3kl9 — APPROVED** [review]
