### PR TITLE
Fixes bugs with relationships and graphql Date

### LINKED ISSUE #125: Bug Match Relationship with Team
The master can't run because it can't establish a relationship with the Teams

### PR DESCRIPTION
**Pull request by larsvandriel**
Fixes #125

### CODE REVIEW

**Review by MindHawk — DISMISSED** [review]

File: src/main/java/com/fontys/api/entities/Match.java [hunk 1]
```diff
@@ -16,13 +16,13 @@
     @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
     private Integer id;
 
-    @OneToMany(fetch = FetchType.EAGER)
+    @OneToOne
```
Comment (lmtjanssen) [inline src/main/java/com/fontys/api/entities/Match.java]: Should be ManyToOne as multiple matches can have the same team

File: src/main/java/com/fontys/api/entities/Match.java [hunk 2]
```diff
@@ -16,13 +16,13 @@
...
     private Team teamHome;
 
-    @OneToMany(fetch = FetchType.EAGER)
+    @OneToOne
```
Comment (lmtjanssen) [inline src/main/java/com/fontys/api/entities/Match.java]: Should be ManyToOne as multiple matches can have the same team

File: src/main/java/com/fontys/api/entities/Match.java [hunk 3]
```diff
@@ -16,13 +16,13 @@
...
     private Team teamAway;
 
-    @OneToMany(fetch = FetchType.EAGER)
+    @OneToOne
```
Comment (lmtjanssen) [inline src/main/java/com/fontys/api/entities/Match.java]: Should be ManyToOne as multiple matches can have the same team

**Review by lmtjanssen — DISMISSED** [review]

**Review by chf3kl9 — APPROVED** [review]

**Review by MichielLangen — APPROVED** [review]
